name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: dotnet build SzpitalV1
